// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHyWucp1_HQUJEOHs3_ViRogxiGwMF1do',
    appId: '1:838754469371:web:48a0db47fbf64e3d9f375e',
    messagingSenderId: '838754469371',
    projectId: 'h3-mobie',
    authDomain: 'h3-mobie.firebaseapp.com',
    storageBucket: 'h3-mobie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMiTIrrBHgRWvoTd6C97tvkYPXIwiMzaY',
    appId: '1:838754469371:android:e8b6ea96a4cf968a9f375e',
    messagingSenderId: '838754469371',
    projectId: 'h3-mobie',
    storageBucket: 'h3-mobie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpskCX9S_1rD8Y6ASVsA9ClVrA-3jd9Q8',
    appId: '1:838754469371:ios:91c264e46c422f469f375e',
    messagingSenderId: '838754469371',
    projectId: 'h3-mobie',
    storageBucket: 'h3-mobie.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpskCX9S_1rD8Y6ASVsA9ClVrA-3jd9Q8',
    appId: '1:838754469371:ios:91c264e46c422f469f375e',
    messagingSenderId: '838754469371',
    projectId: 'h3-mobie',
    storageBucket: 'h3-mobie.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHyWucp1_HQUJEOHs3_ViRogxiGwMF1do',
    appId: '1:838754469371:web:17bbd4ee270884fb9f375e',
    messagingSenderId: '838754469371',
    projectId: 'h3-mobie',
    authDomain: 'h3-mobie.firebaseapp.com',
    storageBucket: 'h3-mobie.firebasestorage.app',
  );

}