import 'package:demo/Screen/about_movie.dart';
import 'package:demo/Screen/detail_movies.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Required for Firebase initialization
import 'package:introduction_screen/introduction_screen.dart';
import 'package:velocity_x/velocity_x.dart';
import 'package:flutter/foundation.dart'; // For kIsWeb


import 'Screen/home_screen.dart'; // Assuming HomeScreen is defined here
import 'package:demo/signup_screen.dart'; // Your signup screen
import 'firebase_options.dart'; // Generated by flutterfire configure

import 'package:demo/Screen/movie_play.dart';
import 'package:demo/Screen/search_movie.dart';
import 'package:demo/Screen/FAQ.dart';


Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (kIsWeb) {
    // Ensure proper Firebase initialization for Web
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.web,
    );
  } else {
    // Use normal Firebase initialization for Android/iOS
    await Firebase.initializeApp();
  }

  runApp(const MyApp());
}
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final List<PageViewModel> pages = <PageViewModel>[
      PageViewModel(
        image: Image.network('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgUy9_d5L4jg1UqyeWAkFJuCWKJDkW9EKB8g&s'),
        title: 'Welcome To Our Movie App',
        body: 'Millions of movies to explore!',
        decoration: const PageDecoration(
          titleTextStyle: TextStyle(color: Colors.red, fontWeight: FontWeight.w700, fontSize: 36),
          bodyTextStyle: TextStyle(color: Colors.white, fontWeight: FontWeight.w500, fontSize: 20.0),
        ),
      ),
      PageViewModel(
        image: Image.network('https://static0.moviewebimages.com/wordpress/wp-content/uploads/2024/06/a-quiet-place-day-one-movie-poster.jpg'),
        title: 'Enjoy with us',
        body: 'Discover curated playlists and recommendations.',
        decoration: const PageDecoration(
          titleTextStyle: TextStyle(color: Colors.white, fontWeight: FontWeight.w700, fontSize: 36),
          bodyTextStyle: TextStyle(color: Colors.white, fontWeight: FontWeight.w500, fontSize: 20.0),
        ),
      ),
      PageViewModel(
        image: Image.network('https://static0.moviewebimages.com/wordpress/wp-content/uploads/2024/06/a-quiet-place-day-one-movie-poster.jpg'),
        title: 'Let\'s Watch Movies',
        body: 'Start your movie marathon now!',
        decoration: const PageDecoration(
          titleTextStyle: TextStyle(color: Colors.red, fontWeight: FontWeight.w700, fontSize: 36),
          bodyTextStyle: TextStyle(color: Colors.white, fontWeight: FontWeight.w500, fontSize: 20.0),
        ),
      ),
    ];

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Builder(
        builder: (context) => IntroductionScreen(
          pages: pages,
          done: const Text('Finish', style: TextStyle(color: Colors.white)),
          onDone: () {
            Navigator.pushReplacement(
              context,
              MaterialPageRoute(builder: (context) => const SignupScreen()),
            );
          },
          next: const Text('Proceed', style: TextStyle(color: Colors.white)),
          showSkipButton: true,
          skip: TextButton(
            child: const Text('Skip', style: TextStyle(color: Colors.white)),
            onPressed: () {
              Navigator.pushReplacement(
                context,
                MaterialPageRoute(builder: (context) => const SignupScreen()),
              );
            },
          ),
          dotsDecorator: DotsDecorator(
            color: Colors.grey,
            activeColor: Colors.white,
            size: const Size(10.0, 10.0),
            activeSize: const Size(22.0, 10.0),
            activeShape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(25.0),
            ),
          ),
          globalBackgroundColor: Colors.black54,
        ),
      ),
    );


    // return MaterialApp(
    //   debugShowCheckedModeBanner: false,
    //   home: FAQPage(),
    // );
    // return const MaterialApp(
    //   debugShowCheckedModeBanner: false,
    //   home: SignupScreen(),
    // );

    // return const MaterialApp(
    //   debugShowCheckedModeBanner: false,
    //   home: MovieDetailsPage(dataFromIntroduction: null, ),
    // );

    // return const MaterialApp(
    //   debugShowCheckedModeBanner: false,
    //   home: MoviePlayPage(dataFromIntroduction: null),
    // );

    // return const MaterialApp(
    //   debugShowCheckedModeBanner: false,
    //   home: MovieDetailsScreen(movieId: 1, dataFromIntroduction:  null),
    // );
  }
}
